### ISSUE TITLE
[Feature Request] Allow to specify Issuer URL when auth is enabled.

### ISSUE THREAD

**Issue by jrpedrianes** [temporalio/ui-server#193]
### Is your feature request related to a problem? Please describe.

I'm trying to integrate [Fusionauth](https://fusionauth.io/) as an OIDC Provider, and I can't do it because we don't have correlated the IssuerURL, discovered requesting `.well-known/openid-configuration`  and the `Provider URL` configured. To "fix" this, I think that `ui-server` could add support to pass the IssuerURL when the OIDC is created. 

Reading the 'go-oidc' code seems that this behaviour, `Provider URL` and `IssuerURL` are not equal in Azure too, https://github.com/coreos/go-oidc/blob/2d47dd95152744f41009de5797efe6cc07832a41/oidc/oidc.go#L72 son adding this feature others IPDs can be supported.

### Describe the solution you'd like

To solve this I think that we can add the following lines around here: https://github.com/temporalio/ui-server/blob/b3d79f14d697ba46b47375232cac79763198ad1e/server/routes/auth.go#L61 and creating the related configuration.

```
	if providerCfg.IssuerURL {
		ctx = oidc.InsecureIssuerURLContext(ctx, providerCfg.IssuerURL)
	}

	provider, err := oidc.NewProvider(ctx, providerCfg.ProviderUrl)
```

If you want, I think that I can create a PR including this. I'm not a go developer but I think that I can do it. (Only I need the config name to use)

**Comment by feedmeapples** [comment]
@jrpedrianes yea would be great if can you draft a PR and validate with your provider that the changes help address the issue. Just to be sure, you've tried running the UI with other providers such as Google and it worked for you right? The issue is specifically with Fusionauth? 

For reference to help you save some time, here is an example PR that adds a new configuration option https://github.com/temporalio/ui-server/pull/194 . The touched files also include configuration for auth that you would update

**Comment by jrpedrianes** [comment]
Hello, I have it working using FushionnAuth, works perfect but I need to use the default tenant and I want to use another. This error is more or less related to how FushionAuth handles multitenancy.

This weekend I'll push a PR with the modifications I think to do to support this kind of behaviour: the provider URL is different from the IssuerURL.
